### ISSUE TITLE
debug messages in /var/log/messages

### ISSUE THREAD

**Issue by mepreston** [funnelfiasco/copr-cherrytree#17]
FC35
cherrytree-future-0.99.46.20220222git0f84c12-1.fc35.x86_64
I'm getting a debug message from cherrytree written to my /var/log/messages file every 5 minutes.
I'm not aware of having enabled debugging.  Is this something related to the build?

Mar  2 14:03:15 xxxxxxx cherrytree[1788]: [2022-03-02 14:03:15.872] [   ] [debug] autosave: no needs to save file

the latest KDE/Plasma has polluted messages enough as is so anything to reduce logging to messages would be a help.

**Comment by funnelfiasco** [comment]
Well it's not something that I've *intentionally* done. 🙂 I'll take a look.

Do you happen to know if this is new behavior? If so, when did it first appear?

**Comment by mepreston** [comment]
it isn't new, these have been logged for more than a year at least.  I've searched several times in the past for any info on debug in cherrytree and haven't found anything posted.  I've been though the config file and didn't see anything there.  I was thinking there might be a build flag accidentally causing this? there are other debug messages, this is he one that is logged everything because of autosave being enabled and set to 5 minute.

**Comment by funnelfiasco** [comment]
Well I was ready to say I'm not seeing this on my F35 Plasma system, but it turns out that my log lines say plasmashell instead of cherrytree:

~~~~
Mar  3 08:46:00 fpgm plasmashell[5108]: [2022-03-03 08:46:00.698] [   ] [debug] autosave: no needs to save file
~~~~

If you run `cherrytree` from the command line, you'll see the same messages. I just made a test build without `-DCMAKE_BUILD_TYPE=Debug`, which has no effect on this (that's what I expected. That option only controls whether debuginfo files are built, not the runtime logging).

This doesn't appear to be an issue in the packaging. It looks like Cherrytree is always emitting debug messages, even if it's not writing to the debug log file. I suggest you [file an issue upstream](https://github.com/giuspen/cherrytree/issues). I'm not sure if it's an issue in Cherrytree itself or perhaps in the spdlog library that it uses.
